# see me at: http://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyterlab/jupyterlab_server/master/docs/rest-api.yml#/default
swagger: "2.0"
info:
  title: JupyterLab Server
  description: The REST API for JupyterLab Server
  version: 1.0.0
  license:
    name: BSD-3-Clause
schemes: [http, https]
basePath: /lab/api
produces:
  - application/json
consumes:
  - application/json

paths:
  /listings/@jupyterlab/extensionmanager-extension/listings.json:
    get:
      summary: Get Extension Listings Specs
      description: |
        Gets the list of extension metadata for the application.
      responses:
        "200":
          description: The Extension Listing specs
          schema:
            type: object
            properties:
              blocked_extension_uris:
                type: array
                description: list of blocked extension uris
                items:
                  type: string
              allowed_extension_uris:
                type: array
                description: list of allowed extension uris
                items:
                  type: string
              blocked_extensions:
                type: array
                description: list of blocked extensions
                items:
                  $ref: "#/definitions/ListEntry"
              allowed_extensions:
                type: array
                description: list of blocked extensions
                items:
                  $ref: "#/definitions/ListEntry"

  /settings/:
    get:
      summary: Get Settings List
      description: |
        Gets the list of all application settings data
      responses:
        "200":
          description: The Application Settings Data
          schema:
            type: object
            properties:
              settings:
                type: array
                description: List of application settings entries
                items:
                  $ref: "#/definitions/SettingsEntry"

  /settings/{schema_name}:
    get:
      summary: Get the settings data for a given schema
      description: |
        Gets the settings data for a given schema
      parameters:
        - name: schema_name
          description: Schema Name
          in: path
          required: true
          type: string
      responses:
        "200":
          description: The Settings Data
          schema:
            $ref: "#/definitions/SettingsEntry"
    put:
      summary: Override the settings data for a given schema
      description: |
        Overrides the settings data for a given schema
      parameters:
        - name: schema_name
          description: Schema Name
          in: path
          required: true
          type: string
        - name: body
          description: raw settings data
          in: body
          schema:
            type: object
            properties:
              raw:
                type: string
      responses:
        "204":
          description: The setting has been updated

  /themes/{theme_file}:
    get:
      summary: Get the settings data for a given schema
      description: |
        Gets the settings data for a given schema
      parameters:
        - name: theme_file
          description: Theme file path
          in: path
          required: true
          type: string
      responses:
        "200":
          description: The Theme File

  /translations/:
    get:
      summary: Get Translation Bundles
      description: |
        Gets the list of translation bundles
      responses:
        "200":
          description: The Extension Listing specs
          schema:
            type: object
            properties:
              data:
                type: object
                additionalProperties:
                  $ref: "#/definitions/TranslationEntry"
              message:
                type: string

  /translations/{locale}:
    get:
      summary: Get the translation data for locale
      description: |
        Gets the translation data for a given locale
      parameters:
        - name: local
          description: Locale name
          in: path
          required: true
          type: string
      responses:
        "200":
          description: The Local Data
          schema:
            type: object
            properties:
              data:
                type: object
              message:
                type: string

  /workspaces/:
    get:
      summary: Get Workspace Data
      description: |
        Gets the list of workspace data
      responses:
        "200":
          description: The Workspace specs
          schema:
            type: object
            properties:
              workspaces:
                type: object
                properties:
                  ids:
                    type: array
                    items:
                      type: string
                  values:
                    type: array
                    items:
                        $ref: "#/definitions/Workspace"

  /workspaces/{space_name}:
    get:
      summary: Get the workspace data for name
      description: |
        Gets the workspace data for a given workspace name
      parameters:
        - name: space_name
          description: Workspace name
          in: path
          required: true
          type: string
      responses:
        "200":
          description: The Workspace Data
          schema:
            $ref: "#/definitions/Workspace"

    put:
      summary: Override the workspace data for a given name
      description: |
        Overrides the workspace data for a given workspace name
      parameters:
        - name: space_name
          description: Workspace Name
          in: path
          required: true
          type: string
        - name: body
          description: raw workspace data
          in: body
          schema:
            $ref: "#/definitions/Workspace"
      responses:
        "204":
          description: The workspace has been updated

    delete:
      summary: Delete the workspace data for a given name
      description: |
        Deletes the workspace data for a given workspace name
      parameters:
        - name: space_name
          description: Workspace Name
          in: path
          required: true
          type: string
      responses:
        "204":
          description: The workspace has been deleted

# Descriptions of common responses
responses:
  NotFound:
    description: The specified resource was not found
  Unauthorized:
    description: Authentication/Authorization error

definitions:
  ListEntry:
    type: object
    properties:
      name:
        type: string
      regexp:
        type: string
      type:
        type: string
      reason:
        type: string
      creation_date:
        type: string
      last_update_date:
        type: string
  SettingsEntry:
    type: object
    properties:
      id:
        type: string
      schema:
        type: object
      version:
        type: string
      raw:
        type: string
      settings:
        type: object
      warning:
        type: string
      last_modified:
        type: string
      created:
        type: string
  TranslationEntry:
    type: object
    properties:
      data:
        type: object
        properties:
          displayName:
            type: string
          nativeName:
            type: string
      message:
        type: string
  Workspace:
    type: object
    properties:
      data:
        type: object
      metadata:
        type: object
        properties:
          id:
            type: string
          last_modified:
            type: string
          created:
            type: string
